# Generated by Django 3.2.8 on 2021-10-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20211020_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Year of Death'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book.', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_en',
            field=models.CharField(help_text='Name of the language in English:', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_native',
            field=models.CharField(help_text='Native name of the lanaguge:', max_length=20),
        ),
    ]
